export const sideItems = [
  { name: "carbon:home", text: "Home" },
  { name: "lets-icons:order", text: "Orders" },
  ,
  { name: "tdesign:app", text: "Products" },
  ,
  { name: "carbon:delivery-truck", text: "Delivery" },
  ,
  { name: "nimbus:marketing", text: "Marketing" },
  ,
  { name: "tabler:brand-google-analytics", text: "Analytics" },
  ,
  { name: "ic:round-payments", text: "Payments" },
  { name: "ph:navigation-arrow-bold", text: "Tools" },
  { name: "tabler:discount-2", text: "Discounts" },
  { name: "fluent:people-audience-24-regular", text: "Audience" },
  { name: "pajamas:appearance", text: "Appearance" },
  { name: "gravity-ui:thunderbolt", text: "Plugins" },
];
