export const sideItems = [
  { name: "carbon:home", text: "Home" },
  { name: "carbon:shopping-cart", text: "Orders" },
  ,
  { name: "carbon:shopping-bag", text: "Products" },
  ,
  { name: "carbon:delivery-parcel", text: "Delivery" },
  ,
  { name: "nimbus:marketing", text: "Marketing" },
  ,
  { name: "carbon:analytics", text: "Analytics" },
  ,
  { name: "fluent:payment-20-regular", text: "Payments" },
  { name: "carbon:tools", text: "Tools" },
  { name: "ic:outline-discount", text: "Discounts" },
  { name: "fluent:people-audience-24-regular", text: "Audience" },
  { name: "pajamas:appearance", text: "Appearance" },
  { name: "gravity-ui:thunderbolt", text: "Plugins" },
];
